/**
 * Do not edit this file.
 * This file is automatic generated to get type help.
 */

import { combineStores } from "dob"
import { ArticleAction, ArticleStore } from "../stores/article"

const stores = combineStores({ ArticleAction, ArticleStore })

export { stores }
